name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH and known hosts
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/github_action
          chmod 600 ~/.ssh/github_action
          ssh-keyscan $VPS_IP >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.POLLS_DJANGO_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}

      # Step 3: Deploy and restart services
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_action $VPS_USER@$VPS_IP << 'EOF'
          cd /home/ubuntu/polls
          git pull origin main
          source venv/bin/activate
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          EOF
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_IP: ${{ secrets.VPS_IP }}
